const data = {
    child:[
        {
            column:[
                {value:"Johan"},
                {value:"27"}
            ]
        },
        {
            column:[
                {value:"Jeison"},
                {value:"28"}
            ]
        },
        {
            column:[
                {value:"Julian"},
                {value:"27"}
            ]
        },
        {
            column:[
                {value:"Juan"},
                {value:"28"}
            ]
        },
        {
            column:[
                {value:"Jose"},
                {value:"27"}
            ]
        },
        {
            column:[
                {value:"Johana"},
                {value:"28"}
            ]
        },
        {
            column:[
                {value:"Jenny"},
                {value:"27"}
            ]
        },
        {
            column:[
                {value:"Jessica"},
                {value:"28"}
            ]
        }
    ]
};